GET http://localhost:3000/products

### craete a product

POST http://localhost:3000/products

### get a product by id

GET  http://localhost:3000/products/id


### uodate a product by id

  PATCH http://localhost:3000/products/id


### delete a product by id

DELETE http://localhost:3000/products/id

### 
GET http://localhost:3000/abc
